kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arena
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - deployments
  - nodes
  - nodes/*
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - services/proxy
  verbs:
  - get
