apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ksonnet.io/component: pipeline
  name: mysql-pv-claim
  namespace: kubeflow
spec:
  accessModes:
  - ReadWriteOnce
  selector:
    matchLabels:
      app: pipeline-mysql
  resources:
    requests:
      storage: 100Gi