apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-mysql-pv
  labels:
    failure-domain.beta.kubernetes.io/zone: cn-beijing-e
    failure-domain.beta.kubernetes.io/region: cn-beijing
    app: pipeline-mysql
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: "alicloud/disk"
    fsType: "ext4"
    options:
      volumeId: mysql-volume-id